  - name: Install bundler and other prerequirements
    gem:
      name: "{{ item }}"
      user_install: no
      state: present
    with_items:
    - bundler
  - name: Install ruby-awstools
    git:
      repo: https://github.com/lnxjedi/ruby-awstools.git
      dest: /usr/local/lib/ruby-awstools
  - name: Symlink rawstools binaries
    block:
    - command: ls
      args:
        chdir: /usr/local/lib/ruby-awstools/bin
      register: rawsbinaries
    - file:
        path: /usr/local/bin/{{ item }}
        src: /usr/local/lib/ruby-awstools/bin/{{ item }}
        state: link
      with_items: "{{ rawsbinaries.stdout_lines }}"
  - name: Run bundle install
    command: /usr/local/bin/bundle install
    args:
      chdir: /usr/local/lib/ruby-awstools
      creates: /usr/local/share/gems/gems/aws-sdk*
